- name: Fix time sync
  hosts: all
  become: yes

  tasks:
    - name: Install chrony
      package:
        name: chrony
        state: present

    - name: Enable and start chrony
      service:
        name: chronyd
        state: started
        enabled: yes

    - name: Force time sync
      command: chronyc -a makestep
