- name: SoftdPAC network remediation
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Fix SoftdPAC container IP configuration
  condition: >
    event.payload is defined and
    event.payload.trigger is defined and
    "SoftdPAC network detected" in event.payload.trigger and
    event.payload.host is defined and
    event.payload.value is defined

  action:
    run_job_template:
      name: SoftdPAC Network
      organization: Default
      job_args:
        extra_vars:
          target_host: "{{ event.payload.host }}"
          ip_info: "{{ event.payload.value }}"
