- name: SoftdPAC network remediation
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: FIx SoftdPAC continer IP configurtaion 
      condition: event.payload.trigger is defined and "SoftdPAC network detected" in event.payload.trigger
      action:
        run_job_template:
          name: SoftdPAC Network
          organization: Default
          job_args:
            extra_vars:
              target_host: "{{event.payload.host}}"
