- name: Zabbix webhook listener
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: High CPU detected 
      condition: true
      action:
        run_job_template:
          name: Deply
          organization: Default
