- name: Zabbix webhook listener
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: High CPU detected 
      condition: event.payload.cpu_value is defined and (event.payload.cpu_value | int >= 90)
      action:
        run_job_template:
          name: Deploy
          organization: Default
